/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    finishedWork: FinishedWork;
    services: Service;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    finishedWork: FinishedWorkSelect<false> | FinishedWorkSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    homePage: HomePage;
    businessInfo: BusinessInfo;
  };
  globalsSelect: {
    homePage: HomePageSelect<false> | HomePageSelect<true>;
    businessInfo: BusinessInfoSelect<false> | BusinessInfoSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Two photos of the same job. Only use a pair where the before and after are genuinely the same place.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Used in links. Ask Pedro before changing an existing one.
   */
  slug: string;
  /**
   * Lower numbers show first.
   */
  sortOrder: number;
  /**
   * The damaged/unfinished state.
   */
  before: number | Media;
  /**
   * The finished work.
   */
  after: number | Media;
  title: string;
  /**
   * Short label above the title, e.g. "Exterior" / "Exteriores".
   */
  kind: string;
  summary: string;
  /**
   * Describes the before photo for screen readers.
   */
  beforeAlt: string;
  /**
   * Describes the after photo for screen readers.
   */
  afterAlt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Internal note so you can find this photo again. Not shown on the site.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Single photos of completed work, where there is no before shot.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishedWork".
 */
export interface FinishedWork {
  id: number;
  image: number | Media;
  /**
   * Lower numbers show first.
   */
  sortOrder: number;
  /**
   * Shown under the photo.
   */
  caption: string;
  /**
   * Describes the photo for screen readers.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Used in links. Ask Pedro before changing an existing one.
   */
  slug: string;
  /**
   * Lower numbers show first.
   */
  sortOrder: number;
  /**
   * Optional. Only some services have a photo.
   */
  image?: (number | null) | Media;
  name: string;
  /**
   * One line, used on the home page and in the quote form.
   */
  short: string;
  body: string;
  /**
   * The specifics of what this service covers.
   */
  detail?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Describes the photo for screen readers.
   */
  imageAlt?: string | null;
  /**
   * Optional. Other words a visitor might use for this, comma separated. The name itself is already matched.
   */
  extraKeywords?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editors can change content but not users or settings.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'finishedWork';
        value: number | FinishedWork;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  slug?: T;
  sortOrder?: T;
  before?: T;
  after?: T;
  title?: T;
  kind?: T;
  summary?: T;
  beforeAlt?: T;
  afterAlt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "finishedWork_select".
 */
export interface FinishedWorkSelect<T extends boolean = true> {
  image?: T;
  sortOrder?: T;
  caption?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  slug?: T;
  sortOrder?: T;
  image?: T;
  name?: T;
  short?: T;
  body?: T;
  detail?:
    | T
    | {
        text?: T;
        id?: T;
      };
  imageAlt?: T;
  extraKeywords?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The wording on the home page. Photos and services are edited separately, under Content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  /**
   * Small line above the headline.
   */
  eyebrow: string;
  /**
   * First line.
   */
  h1a: string;
  /**
   * Second line.
   */
  h1b: string;
  /**
   * Third line, shown in blue.
   */
  h1accent: string;
  /**
   * The paragraph under the headline. Two sentences reads best; much longer pushes the photo below the fold on a phone.
   */
  lede: string;
  /**
   * Shown in a row across the page. Three fits the layout; four gets cramped.
   */
  valueProps: {
    title: string;
    body: string;
    id?: string | null;
  }[];
  /**
   * Above the services grid.
   */
  servicesEyebrow: string;
  servicesTitle: string;
  /**
   * Above the before/after strip.
   */
  proofEyebrow: string;
  proofTitle: string;
  proofLede: string;
  /**
   * Above the numbered steps. The steps themselves also appear on the Services page, so they are not editable here.
   */
  processEyebrow: string;
  processTitle: string;
  /**
   * Above the service-area section.
   */
  areaEyebrow: string;
  areaTitle: string;
  /**
   * Follows the list of cities, which is built from Business Info.
   */
  areaLede: string;
  /**
   * The clickable line in Google results. Around 60 characters before it is cut off.
   */
  metaTitle: string;
  /**
   * The grey text under it in Google results. Around 155 characters before it is cut off.
   */
  metaDescription: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Phone, email and service area. These appear on every page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businessInfo".
 */
export interface BusinessInfo {
  id: number;
  /**
   * As it should read on the page, e.g. (612) 636-5194. The call and text links are built from this automatically.
   */
  phone: string;
  email: string;
  /**
   * Full URL to the Facebook page.
   */
  facebook?: string | null;
  /**
   * Cities named as examples on the site. Not translated — these are place names.
   */
  namedCities?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  name: string;
  /**
   * Used in page titles and the estimate emails.
   */
  nameFull: string;
  /**
   * The Spanish-spoken badge. A brand phrase, shown as-is in both languages.
   */
  spanish: string;
  /**
   * Canonical URL, no trailing slash. Feeds the sitemap and social previews — wrong values here break search indexing.
   */
  siteUrl: string;
  /**
   * Display form, e.g. bluewingspainting.com
   */
  domain: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  eyebrow?: T;
  h1a?: T;
  h1b?: T;
  h1accent?: T;
  lede?: T;
  valueProps?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  servicesEyebrow?: T;
  servicesTitle?: T;
  proofEyebrow?: T;
  proofTitle?: T;
  proofLede?: T;
  processEyebrow?: T;
  processTitle?: T;
  areaEyebrow?: T;
  areaTitle?: T;
  areaLede?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "businessInfo_select".
 */
export interface BusinessInfoSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  facebook?: T;
  namedCities?:
    | T
    | {
        name?: T;
        id?: T;
      };
  name?: T;
  nameFull?: T;
  spanish?: T;
  siteUrl?: T;
  domain?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}